### ISSUE TITLE
Issues with PlayerHandle Triggers

### ISSUE THREAD

**Issue by fatjosephina** [fatjosephina/simple-machines#38]
> **Issue 1: All PlayerHandle Triggers spawn as active and enabled**
> 
> **Repro Steps:**
> 1. Start the game
> 2. Note that all PlayerHandle Triggers are active and enabled, despite the fact that their default state in the prefab is that only the trigger named "UHandle" is active, and despite the fact that the animator disables them
> 
> **Expected Results:**
> The player spawns in, and all of its handle triggers are disabled except for "UHandle", because the player is in the IdleDown animation.
> 
> **Actual Results:**
> All four PlayerHandle Triggers spawn as active and enabled.

Solved.
**____________________________________________________________________________________________________________________________________**

**Issue 2: PlayerHandle objects (child objects are player) are detected as being part of the player**

**Repro Steps:**
1. Start the game
2. Walk out of the spawn (light colored zone where the player spawns)
3. Note that the Quota in the top left corner will flash red whenever the PlayerHandle triggers touch the spawn, even though the player itself is not touching the spawn

**Expected Results:**
The handle triggers, although they are child objects of the player, are not detected as being part of the player because they do not have the "Player" tag, but instead have the "PlayerHandle" tag. Therefore, when they touch the spawn, the red flashing should not be activated.

**Actual Results:**
When the triggers of the player's handles touch the spawn, the red flashing quota in the top left corner is activated.

**Comment by dantogno** [comment]
All of the handles are enabled on the Player prefab.
![image](https://user-images.githubusercontent.com/3150710/99409212-bd4c8680-28b6-11eb-878e-addfd2de77d9.png)

**Comment by dantogno** [comment]
If I disable them in the prefab (and save the prefab) the instance of it that is created in the game starts with these game objects disabled:
![image](https://user-images.githubusercontent.com/3150710/99409404-f1c04280-28b6-11eb-9803-4bfeed738cbc.png)

**Comment by dantogno** [comment]
Oh, I see, you are talking about the actual BoxCollider2D  components on this object. That is unclear in your issue writeup.

**Comment by dantogno** [comment]
The box collider components all appear to be enabled in the prefab.
![image](https://user-images.githubusercontent.com/3150710/99410554-37313f80-28b8-11eb-9040-dbac102f2e3f.png)

**Comment by dantogno** [comment]
I think the reason things aren't disabling as you expect based on your animations is because it seems like only the idle poses try to do this, but the walk poses don't. As soon as you leave an idle animation, things not explicitly controlled by the animation will go to their default "unanimated" state. 

My advice would be to control the box colliders in script (or bolt) as opposed to animations. Alternatively you could try to add in control over the colliders into your walk anims. But I think this is a bad solution since you will have to try to set this up in a bunch of different files, there are many points of failure.

**Comment by dantogno** [comment]
Ok to address you second issue, in the future, clarify what "the spawn" means.  Be specific (gameobject name, script, etc.). 

Where is the code that is detecting when something enters a trigger to make the text flash? I think we need to look at the specific OnTriggerEnter (or whatever it is) that is being called at the wrong time to see what's happening, and I don't know how to find it.

**Comment by fatjosephina** [comment]
> Oh, I see, you are talking about the actual BoxCollider2D components on this object. That is unclear in your issue writeup.

For me, I would like for either one to work. Either the entire game object is disabled or the BoxCollider2D is disabled. The main thing is that I just don't want all 4 to be active and enabled when the game starts. I tried testing out disabling the BoxCollider2D's in the prefab, but they are still enabled when I start the game.

**Comment by fatjosephina** [comment]
> My advice would be to control the box colliders in script (or bolt) as opposed to animations. Alternatively you could try to add in control over the colliders into your walk anims. But I think this is a bad solution since you will have to try to set this up in a bunch of different files, there are many points of failure.

How would you recommend doing this? Would I make a variable for all 4, then assign them by looking for a name in the object's children, and then change which one is active based on the animation of the player? It sounds like it might get complicated quickly, but I will try it.

**Comment by fatjosephina** [comment]
> Ok to address you second issue, in the future, clarify what "the spawn" means. Be specific (gameobject name, script, etc.).
> 
> Where is the code that is detecting when something enters a trigger to make the text flash? I think we need to look at the specific OnTriggerEnter (or whatever it is) that is being called at the wrong time to see what's happening, and I don't know how to find it.

My bad, I should have specified that. The spawn is the game object in the hierarchy named Spawn. The code that triggers this is on the Player, in the PlayerScore script. It is the OnTriggerEnter2D() method which checks for an object tagged "Goal". I don't get why it is activated when the child objects touch the spawn, even when the parent (Player object) doesn't.

**Comment by fatjosephina** [comment]
> My advice would be to control the box colliders in script (or bolt) as opposed to animations. Alternatively you could try to add in control over the colliders into your walk anims. But I think this is a bad solution since you will have to try to set this up in a bunch of different files, there are many points of failure.

Alright, I have added this code to the PlayerMovement script:
`
    private BoxCollider2D uHandle;
    private BoxCollider2D dHandle;
    private BoxCollider2D rHandle;
    private BoxCollider2D lHandle;`

    private void Start()
    {
        uHandle = transform.Find("UHandle").GetComponent<BoxCollider2D>();
        dHandle = transform.Find("DHandle").GetComponent<BoxCollider2D>();
        rHandle = transform.Find("RHandle").GetComponent<BoxCollider2D>();
        lHandle = transform.Find("LHandle").GetComponent<BoxCollider2D>();
    }`

Should I update the rest of the script to use these values?

**Comment by dantogno** [comment]
I think I would make an `UpdateHandles()` method to handle it but I am curious what should happen when the player is moving diagonally. What is the intended behavior here in general? What are the handles and when should each show up?

**Comment by fatjosephina** [comment]
> I think I would make an `UpdateHandles()` method to handle it but I am curious what should happen when the player is moving diagonally. What is the intended behavior here in general? What are the handles and when should each show up?

I think it makes the most sense for the active handles to reflect what the animation is showing, rather than how the player is actually moving. So, when the player is moving diagonally, whichever animation takes priority would be the one whose handle is enabled.

There are 4 handle triggers, one for each direction. The handles are located on the player's back. So, when the player is facing up, DHandle is active. When they are facing down, UHandle is active. When they are facing right, LHandle is active. Finally, when they are facing left, RHandle is active. The handles are used by my enemy to grab the player.
