### ISSUE TITLE
Issue with Enemy Handle Triggers

### ISSUE THREAD

**Issue by fatjosephina** [fatjosephina/simple-machines#39]
**Issue 1: Enemy handle trigger strongly favors left trigger**

**Repro Steps:**
1. Start the game
2. Interact with the enemy by getting close enough to it for it to notice the player chaaracter
3. Notice that the enemy left handle trigger is active, even though its animations dictate that it should not be

**Expected Results:**
The animation events direct the correct handle trigger to be active. When the enemy is facing downwards, the "UHandle" should be active, when it is facing right, the "LHandle" should be active, et cetera.

**Actual Results:**
The left handle trigger "LHandle" is almost always active, while the others are not.

**Comment by dantogno** [comment]
What does "interact with the enemy" mean? Clarify.

**Comment by dantogno** [comment]
You also should clarify what is supposed to happen with a bit more detail.

**Comment by dantogno** [comment]
Looking at the enemy animations with the events ("VulLeft", "VulRight," etc.) I have these questions:

1. Why do you need to have more than one of the same event in the same animation?
1. How do you pass the string parameter into the method that is called from the animation event?

**Comment by dantogno** [comment]
What is the player's strategy supposed to be here? How is a player supposed to interact with the enemy handles?

**Comment by fatjosephina** [comment]
> What does "interact with the enemy" mean? Clarify.

By interact I just meant get close enough to the enemy for it to notice you. I will update this in the issue.

**Comment by fatjosephina** [comment]
> You also should clarify what is supposed to happen with a bit more detail.

Alright, I added some clarifications for this as well.

**Comment by fatjosephina** [comment]
> Looking at the enemy animations with the events ("VulLeft", "VulRight," etc.) I have these questions:
> 
> 1. Why do you need to have more than one of the same event in the same animation?
> 2. How do you pass the string parameter into the method that is called from the animation event?

1. I added more than one of the same event in each animation because I noticed that if the animator transitioned in the middle of the animation, the event would not happen until the next time the animation loops. For example, if I had an event at the start of a walk cycle, and the animation transitioned in the middle of the walk cycle, the event would not happen until the animation restarts its cycle.

2. This all happens in the PlayerHandleColliders class which should probably be renamed now that I look at it. I ended up not using any parameters in the animation event itself. Instead, I created 4 separate methods in the class for each handle orientation which all pass in the corresponding parameter to the EnableHandle() method.

Hopefully these answers make sense, let me know if I missed something/misunderstood or the answer is not clear.

**Comment by fatjosephina** [comment]
> What is the player's strategy supposed to be here? How is a player supposed to interact with the enemy handles?

So the player should be able to basically outmaneuver the enemy and grab one of the enemy's handles. I will say that this is pretty difficult at the moment, but after I get the animations fixed I will alter to code to make it easier. After the player grabs the enemy, the enemy will transition to the vulnerable BeingGrabbed state in the EnemyMovement class. In this state, the enemy is basically defenseless and cannot do anything unless the player lets go of it.

After the player grabs the enemy, they can then drag it into the guillotine to kill it, which I have not added yet.

**Comment by dantogno** [comment]
> > What is the player's strategy supposed to be here? How is a player supposed to interact with the enemy handles?
> 
> So the player should be able to basically outmaneuver the enemy and grab one of the enemy's handles. I will say that this is pretty difficult at the moment, but after I get the animations fixed I will alter to code to make it easier. 

So what is the player's strategy to outmaneuver the enemy?

**Comment by dantogno** [comment]
> > 1. Why do you need to have more than one of the same event in the same animation?
> 
> 1. I added more than one of the same event in each animation because I noticed that if the animator transitioned in the middle of the animation, the event would not happen until the next time the animation loops. For example, if I had an event at the start of a walk cycle, and the animation transitioned in the middle of the walk cycle, the event would not happen until the animation restarts its cycle.


Try setting the animation transitions to have no exit time and 0 duration. The preview image should show the two tracks butted up against one another cleanly with no overlap. Let me know if that enables a behavior where the events never get skipped.

**Comment by fatjosephina** [comment]
> > > What is the player's strategy supposed to be here? How is a player supposed to interact with the enemy handles?
> > 
> > 
> > So the player should be able to basically outmaneuver the enemy and grab one of the enemy's handles. I will say that this is pretty difficult at the moment, but after I get the animations fixed I will alter to code to make it easier.
> 
> So what is the player's strategy to outmaneuver the enemy?

The enemy's turning and movement should be slower than the player's, so the player ideally should be able to juke them and grab them afterwards.

**Comment by fatjosephina** [comment]
> > > 1. Why do you need to have more than one of the same event in the same animation?
> > 
> > 
> > 
> > 1. I added more than one of the same event in each animation because I noticed that if the animator transitioned in the middle of the animation, the event would not happen until the next time the animation loops. For example, if I had an event at the start of a walk cycle, and the animation transitioned in the middle of the walk cycle, the event would not happen until the animation restarts its cycle.
> 
> Try setting the animation transitions to have no exit time and 0 duration. The preview image should show the two tracks butted up against one another cleanly with no overlap. Let me know if that enables a behavior where the events never get skipped.

Alright, I just set this. It seems like the animation events might not be getting skipped anymore, but it is hard to tell. However, the enemy's handles are still having the same problem of almost always favoring the left handle.
