### ISSUE TITLE
Issue with Enemy Vulnerability

### ISSUE THREAD

**Issue by fatjosephina** [fatjosephina/simple-machines#40]
**Issue 1: When the enemy is in a vulnerable state, its handles and animations bug out and error messages appear**

**Repro Steps:**
1. Start the game
2. Grab the enemy 

**Expected Results:**
The enemy can be grabbed and pulled into the guillotine without any errors.

**Actual Results:**
The enemy has very strange behavior, quickly alternating between handles and animations, with many error messages saying "AnimationEvent has no function name specified!"

**Comment by dantogno** [comment]
Give me the design vision for the enemy.

**Comment by dantogno** [comment]
Where is the logic that controls switching through states?
Where is the logic that controls what happens each frame while the enemy is in the vulnerable state?

**Comment by fatjosephina** [comment]
> Give me the design vision for the enemy.

The enemy is kind of like a "foil" to the player, since they can also grab things. The enemy can grab the player and the player can grab the enemy, which hopefully will make for interesting encounters. Neither one can directly kill the other, so they must grab the other one and pull them into the guillotine.

In terms of behavior, I want the enemy to
- Chase after the player while the player is in a certain range (completed)
- Grab the player when they touch the player's handle (completed)
- Once they have grabbed the player, drag them into the guillotine (completed)
- Become vulnerable when the player grabs their handle (in progress, this is where I encounter the bugs #39 and #40)
- Die when they are hit by the guillotine when in a vulnerable state (to do)
- Walk around walls, boxes, etc. instead of walking through them (to do)

**Comment by fatjosephina** [comment]
> Where is the logic that controls switching through states?
> Where is the logic that controls what happens each frame while the enemy is in the vulnerable state?

The states are controlled in the EnemyMovement class. There are basically 3 methods for enemy behavior, BehaveStandard(), BehaveGrabbing(), and BehaveBeingGrabbed(). If the active method between these 3 senses that the conditions for one of the other two have been met, then they will switch the enemy's state. Then, the corresponding method will be called in the DefineState() method which is called in Update().

When the enemy is vulnerable (BeingGrabbed), the BehaveBeingGrabbed() method in the EnemyMovement class is active. This method tells the animator what animation should be played. In the animation itself, the animation events control the enemy's handles during this state. The animation events call the methods from the PlayerHandleColliders class.

**Comment by dantogno** [comment]
First of all, I think this is a cool vision. I think you will probably need to come out with a way to give the player an opening to grab. For example, perhaps the enemy charges the player and then, if it hits a wall first or doesn't get to the player after a bit of time it has an idle or stunned animation / state that gives the player an opening to grab.

**Comment by fatjosephina** [comment]
> First of all, I think this is a cool vision. I think you will probably need to come out with a way to give the player an opening to grab. For example, perhaps the enemy charges the player and then, if it hits a wall first or doesn't get to the player after a bit of time it has an idle or stunned animation / state that gives the player an opening to grab.

This is a good idea, but it might take some extra time to implement. If I end up having some more time, a more clear "stunned" state will definitely be something I will try to implement.
